server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ # 指定注册中心的地址
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true  # 默认为true。如果设置为false，Ribbon将不会从Eureka
                   # 中获得服务列表，而是使用静态配置的服务列表。静态服务
                   # 列表可使用：<client>.ribbon.listOfServers来指定。
                   # 参考：http://projects.spring.io/spring-cloud/
                   # docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka
swagger2:
  ui:
    enabled: true

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                         # 指定数据源
    platform: h2                      # 指定数据源类型
    schema: classpath:schema.sql      # 指定h2数据库的建表脚本
    data: classpath:data.sql          # 指定h2数据库的insert脚本
    username:
    password:
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.spring.august: ERROR