ribbon:
  eureka:
    enabled: true   # 默认为true。如果设置为false，Ribbon将不会从Eureka
                    # 中获得服务列表，而是使用静态配置的服务列表。静态服务
                    # 列表可使用：<client>.ribbon.listOfServers来指定。
                    # 参考：http://projects.spring.io/spring-cloud/
                    # docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka
server:
  port: 8011
spring:
  application:
    name: movie-ribbon-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ # 指定注册中心的地址
#  instance:
#    hostname: ribbon  # 此处，preferIpAddress不设置或者设为false，不能设为true，
                      #否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname
                      #一致时只能检测到一个节点，会造成turbine数据不完整