server:
  port: 9020

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ # 指定注册中心的地址
  instance:
    preferIpAddress: false  #将preferIpAddress设为false或者不设置，否则将会造成在单个主机上测试，Turbine只显示一个图表的情况。

ribbon:
  eureka:
    enabled: true   # 默认为true。如果设置为false，Ribbon将不会从Eureka
                    # 中获得服务列表，而是使用静态配置的服务列表。静态服务
                    # 列表可使用：<client>.ribbon.listOfServers来指定。
                    # 参考：http://projects.spring.io/spring-cloud/
                    # docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka